export const Motivation = [
    "You've got this! 💪🌟",
    "Keep going, you're doing great! 🚀🔥",
    "Believe in yourself and succeed! 🌟✨",
    "Making progress, keep it up! 🙌💯",
    "You're a superstar! 🌟🏆",
    "Stay focused and conquer! 💪✨",
    "Doing fantastic! Keep it up! 👏😄",
    "On fire! Keep going! 🔥🚀",
    "Getting closer to success! 🌟💯",
    "Don't give up, almost there! 💪💥",
    "Every step brings you closer to victory! 🌟✨",
    "Unstoppable! Keep it up! 💪🔥",
    "Rocking it! 🚀🌟",
    "Mastering it! Keep it going! 🎉💯",
    "Got the power to succeed! 💪✨",
    "Doing an amazing job! Keep pushing! 👍🌟",
    "Nailing it! Keep up the great work! 💯👏",
    "Believe in yourself and reach for the stars! 🌟⭐️",
    "On the right track! Keep going! 🚀✨",
    "Doing brilliantly! Keep it up! 🌟👍",
    "Success is just around the corner! Keep pushing! 💪🔥",
    "Whiz! Keep it up! 🌟💯",
    "Champion in the making! 🏆🌟",
    "Keep going, doing awesome! 💪😄",
    "Getting closer to victory with each step! 🌟💯",
    "Got what it takes! Believe in yourself! 💪✨",
    "On fire! Keep up the great work! 🔥👏",
    "Doing fantastic! Keep it going! 🌟🚀",
    "Genius! Keep up the amazing work! 🎉💯",
    "Making great strides! Don't stop now! 💪⭐️",
    "Acing it! Keep up the excellent work! 🌟👍",
    "Unstoppable! Keep pushing! 💪🔥",
    "Rockstar! Keep shining! 🌟💯",
    "Doing an outstanding job! Keep it up! 👏✨",
    "On the path to success! Keep going! 🚀💪",
    "Doing phenomenally well! Keep it up! 🌟👍",
    "So close to victory! Keep pushing forward! 💪💥",
    "Prodigy! Keep up the amazing work! 🎉💯",
    "On your way to becoming a champion! 🏆🌟",
    "Doing awesome! Keep up the great work! 😄👍",
    "Each step brings you closer to triumph! 🌟💯",
    "Capable of greatness! Believe in yourself! 💪✨"
]